language: ruby
bundler_args: --without development
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - ruby-head
  - 1.8.7
notifications:
  email: false
  webhooks:
    urls:
      - https://puppet-dev-community.herokuapp.com/event/travis/
      - http://requestb.in/r189vnr1
    on_success: always
    on_failure: always
    on_start: true
